# Generated by Django 4.1.7 on 2023-04-10 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCom', models.CharField(max_length=10)),
                ('livreCom', models.CharField(max_length=50)),
                ('qteCom', models.IntegerField(verbose_name=50)),
                ('dateCom', models.DateTimeField()),
                ('nomClient', models.CharField(max_length=20)),
                ('prenomClient', models.CharField(max_length=30)),
                ('telephoneClient', models.IntegerField()),
                ('adresseClient', models.CharField(max_length=50)),
                ('moyenPaiementClient', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('sujet', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
    ]
